### ISSUE TITLE
Update State Programmatically

### ISSUE THREAD

**Issue by yuriboeira11tx** [WieFel/hsv_color_pickers#3]
Hello! I would like to thank you for the work done so far, it works perfectly. So, I come to ask if there is a way to programmatically change the cursor to a certain color and not just through ```initialColor```. Because the same only works the first time the widget is initialized for the first time. Any suggestion?

**Comment by WieFel** [comment]
@yuriboeira11tx thanks for your kind words!
You are right. Still, the Widget is missing a way to modify it programmatically from the "outside". This could be done by adding a controller to the widget (still has to be implemented).

Meanwhile I think you could circumvent it by setting a `key` on the widget and re-rendering it when there is a change on the `initialColor` from the outside.

Feel free to look into it yourself and file a PR ;)
Else I will try to have a look at it ASAP...

**Comment by yuriboeira11tx** [comment]
@WieFel thanks for your comment. Could you give me an example using ```key```? I didn't understand how to implement state update via ```key```. Thanks in advance!

**Comment by WieFel** [comment]
I was thinking of something like this, but I actually noticed that is doesn't work properly:
```dart
import 'package:flutter/material.dart';
import 'package:hsv_color_pickers/hsv_color_pickers.dart';

void main() {
  runApp(ExampleApp());
}

class ExampleApp extends StatefulWidget {
  @override
  _ExampleAppState createState() => _ExampleAppState();
}

class _ExampleAppState extends State<ExampleApp> {
  Color color = Colors.green;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: Text("HSV Colors Pickers"),
        ),
        body: Column(
          mainAxisAlignment: MainAxisAlignment.spaceAround,
          children: [
            Container(
              height: 50,
              width: 50,
              color: color,
            ),
            Padding(
              padding: const EdgeInsets.all(8.0),
              child: HuePicker(
                // this key here lets HuePicker re-init when color changes
                key: ValueKey(color),
                initialColor: HSVColor.fromColor(color),
                onChanged: (color) {
                  setState(() {
                    this.color = color.toColor();
                  });
                },
                thumbShape: HueSliderThumbShape(
                  color: Colors.white,
                  borderColor: Colors.black,
                  filled: false,
                  showBorder: true,
                ),
              ),
            ),
            TextButton(
              child: const Text("Set to blue"),
              // sets color to blue
              onPressed: () => setState(() => color = Colors.blue),
            )
          ],
        ),
      ),
    );
  }
}

```

A controller needs to be implemented for allowing to change the `HuePicker`'s state from the outside. I will take a look at this asap.

**Comment by WieFel** [comment]
@yuriboeira11tx version `0.2.0` is now available on pub.dev including the new `HueController` for manipulating the state from outside the `HuePicker`!
Check out the readme or the example project for hints on how to use it ;)
